site_name: Discord Documentation

nav:
  - Home: "index.md"
  - Servers: "Task1.md"
  - Server Bot: "Task2.md"
  - Discord Activities: "Task3.md"
  - Troubleshooting: "Trouble.md"
  - Glossary: "Glossary.md"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: '7289DA' 
      accent: '4F545C'   
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: '99AAB5'  
      accent: '2C2F33'   


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/marcangelo1/Discord-Documentation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

copyright: |
  &copy; 2024 <a href=""  target="_blank" rel="noopener">Marc Angelo Arnaldo and Sebastian Taylor</a>